export interface StrategicSupplier {
  companyName: string
  country: string
  website?: string
  email?: string
  phone?: string
  linkedin?: string
  city?: string
  description?: string
  categories: string[]
}

const CHINA: StrategicSupplier[] = [
  { companyName: "Broad Sustainable Building", country: "China", website: "https://www.broad.com", email: "info@broad.com", city: "Changsha", categories: ["prefab-houses", "modular-buildings", "modular-hotels", "hvac"], description: "Pioneer in prefabricated sustainable building systems. 57-storey tower built in 19 days. Strong export to Africa and Middle East." },
  { companyName: "CIMC Modular Building Systems", country: "China", website: "https://www.cimc-modular.com", email: "modular@cimc.com", city: "Shenzhen", categories: ["modular-buildings", "container-homes", "modular-hotels", "modular-villas", "steel-structures"], description: "World's largest container manufacturer. Specializes in modular hotels, resorts, and container homes for hospitality projects. Active in East Africa." },
  { companyName: "China State Construction Engineering (CSCEC)", country: "China", website: "https://www.cscec.com", email: "overseas@cscec.com", city: "Beijing", categories: ["steel-structures", "modular-buildings", "glass-facades", "elevators"], description: "Largest construction company in the world. Extensive experience in African hotel and resort projects." },
  { companyName: "CNBM International", country: "China", website: "https://www.cnbm.com.cn", email: "export@cnbm.com", city: "Beijing", categories: ["cement-manufacturers", "steel-manufacturers", "glass-facades", "sandwich-panels"], description: "China National Building Materials Group. World's largest building materials conglomerate. Full export to 140+ countries including Tanzania." },
  { companyName: "Broad Homes", country: "China", website: "https://www.broadhomes.com", email: "sales@broadhomes.com", city: "Changsha", categories: ["prefab-houses", "modular-buildings", "sandwich-panels"], description: "Leading prefab housing manufacturer. Specializes in export-ready modular homes and villas for resort projects." },
  { companyName: "Capsule Hotel China (Aritco)", country: "China", website: "https://www.aritco.com", email: "export@aritco.com", city: "Shanghai", categories: ["capsule-houses", "modular-hotels", "hotel-furniture"], description: "Leading capsule hotel and modular accommodation manufacturer. Experienced in hospitality projects across Asia and Africa." },
  { companyName: "Haili Heavy Industry", country: "China", website: "https://www.haili.com", email: "sales@haili.com", city: "Changsha", categories: ["steel-structures", "steel-manufacturers", "prefab-houses"], description: "Major steel structure and prefab building manufacturer. Completed 500+ projects in 30+ countries including Africa." },
  { companyName: "Mingze Modular Buildings", country: "China", website: "https://www.mingzemodular.com", email: "info@mingzemodular.com", city: "Guangzhou", categories: ["modular-buildings", "container-homes", "modular-hotels", "modular-villas"], description: "Specialized in export-grade modular buildings for hotels, resorts, and commercial projects. Active in East African market." },
  { companyName: "Shenzhen Sunyoung Modular Building", country: "China", website: "https://www.sunyoungmodular.com", email: "sales@sunyoungmodular.com", city: "Shenzhen", categories: ["container-homes", "modular-hotels", "prefab-houses"], description: "Export-focused modular container home manufacturer. Serving hospitality and resort projects globally." },
  { companyName: "Shanghai Lijing Hotel Furniture", country: "China", website: "https://www.lijingfurniture.com", email: "export@lijingfurniture.com", city: "Shanghai", categories: ["hotel-furniture", "ffe", "ose", "commercial-kitchens"], description: "Top Chinese hotel FF&E manufacturer. Specializes in 5-star hotel furniture, commercial kitchens, and OS&E for hospitality projects worldwide." },
  { companyName: "Guangdong Yotai Kitchen Equipment", country: "China", website: "https://www.yotai.com", email: "info@yotai.com", city: "Guangzhou", categories: ["commercial-kitchens", "ose", "hotel-furniture"], description: "Leading commercial kitchen equipment manufacturer. Exports to 80+ countries. Specializes in hotel and resort kitchen solutions." },
  { companyName: "Jiangsu Zhongnan Construction", country: "China", website: "https://www.zhongnan.com", email: "overseas@zhongnan.com", city: "Nantong", categories: ["steel-structures", "glass-facades", "modular-buildings", "aluminium-systems"], description: "Major steel structure and curtain wall contractor. Completed multiple African hospitality and commercial projects." },
  { companyName: "China Glass Holdings (CGH)", country: "China", website: "https://www.cgh.com.cn", email: "export@cgh.com.cn", city: "Shanghai", categories: ["glass-facades", "aluminium-systems"], description: "Leading glass facade and aluminium systems manufacturer. Strong export to East African construction market." },
  { companyName: "Midea HVAC Global", country: "China", website: "https://www.midea.com", email: "hvac.export@midea.com", city: "Foshan", categories: ["hvac"], description: "World's largest HVAC manufacturer. Full range of commercial HVAC solutions for hotels and resorts. Active in Tanzania." },
  { companyName: "Gree Electric Appliances", country: "China", website: "https://www.gree.com", email: "export@gree.com", city: "Zhuhai", categories: ["hvac"], description: "Major HVAC manufacturer. Specializes in commercial air conditioning for hospitality projects in Africa." },
  { companyName: "LONGi Green Energy", country: "China", website: "https://www.longi.com", email: "sales@longi.com", city: "Xi'an", categories: ["solar-systems"], description: "World's largest solar manufacturer. Complete solar solutions for commercial and hospitality projects. Active in East Africa." },
  { companyName: "JA Solar Technology", country: "China", website: "https://www.jasolar.com", email: "info@jasolar.com", city: "Beijing", categories: ["solar-systems"], description: "Top 5 global solar manufacturer. PV modules and systems for hotel and resort applications in Africa." },
  { companyName: "Trina Solar", country: "China", website: "https://www.trinasolar.com", email: "sales@trinasolar.com", city: "Changzhou", categories: ["solar-systems"], description: "Leading solar PV manufacturer. Distributed generation and utility-scale solutions for African hospitality sector." },
  { companyName: "KONE China", country: "China", website: "https://www.kone.com", email: "info.cn@kone.com", city: "Kunshan", categories: ["elevators"], description: "Global elevator and escalator leader. Extensive installed base in African hotels and commercial buildings." },
  { companyName: "Otis Elevator China", country: "China", website: "https://www.otis.com", email: "china.info@otis.com", city: "Shanghai", categories: ["elevators"], description: "World's largest elevator manufacturer. Strong presence in East African hospitality and commercial projects." },
  { companyName: "Schindler China", country: "China", website: "https://www.schindler.com", email: "china.info@schindler.com", city: "Shanghai", categories: ["elevators"], description: "Premium elevator and escalator solutions. Active in African high-end hotel and resort projects." },
  { companyName: "Baosteel Group", country: "China", website: "https://www.baosteel.com", email: "export@baosteel.com", city: "Shanghai", categories: ["steel-manufacturers", "steel-structures"], description: "World's largest steel producer. Full range of structural steel for construction and prefab buildings. Exports to East Africa." },
  { companyName: "HBIS Group", country: "China", website: "https://www.hbis.com", email: "export@hbis.com", city: "Shijiazhuang", categories: ["steel-manufacturers", "rebar-manufacturers"], description: "Major Chinese steel producer. Rebar, wire rod, and structural steel products. Strong African export channel." },
  { companyName: "Ansteel Group", country: "China", website: "https://www.ansteel.com", email: "export@ansteel.com", city: "Anshan", categories: ["steel-manufacturers", "rebar-manufacturers"], description: "Major steel manufacturer. Rebar, HRC, CRC for construction. Exports to Tanzania and East Africa." },
  { companyName: "Anhui Conch Cement", country: "China", website: "https://www.conch.cn", email: "export@conch.cn", city: "Wuhu", categories: ["cement-manufacturers"], description: "World's largest cement producer (by single operation). Exports bulk and bagged cement to East Africa and Indian Ocean islands." },
  { companyName: "China Resources Cement", country: "China", website: "https://www.crcement.com", email: "export@crcement.com", city: "Guangzhou", categories: ["cement-manufacturers"], description: "Major cement manufacturer. Exports OPC, PPC, and specialized cement grades to African markets." },
  { companyName: "Jiangxi Wannianqing Cement", country: "China", website: "https://www.wnq.com.cn", email: "export@wnq.com.cn", city: "Nanchang", categories: ["cement-manufacturers"], description: "Leading Chinese cement exporter to East Africa. Cost-effective OPC and PPC grades." },
  { companyName: "Shanghai Metal Corporation", country: "China", website: "https://www.smcce.com", email: "sales@smcce.com", city: "Shanghai", categories: ["steel-manufacturers", "steel-structures", "rebar-manufacturers", "sandwich-panels"], description: "Comprehensive steel and building materials exporter. Sandwich panels, steel structures, rebar for construction. One-stop supplier for African projects." },
  { companyName: "Xuzhou Construction Machinery Group (XCMG)", country: "China", website: "https://www.xcmg.com", email: "overseas@xcmg.com", city: "Xuzhou", categories: ["steel-structures"], description: "Major construction machinery and steel structure manufacturer. Active throughout Africa with strong service network." },
  { companyName: "Huafeng Aluminum", country: "China", website: "https://www.huafeng.com", email: "export@huafeng.com", city: "Guangdong", categories: ["aluminium-systems", "glass-facades"], description: "Leading aluminium extrusion and facade systems manufacturer. Exports curtain walls, windows, and doors to East Africa." },
  { companyName: "Guangdong Dongjia Hotel Furniture", country: "China", website: "https://www.dongjia.com", email: "info@dongjia.com", city: "Foshan", categories: ["hotel-furniture", "ffe"], description: "Specialized hotel furniture manufacturer. Full FF&E solutions for international hotel chains. Export experience to Africa." },
  { companyName: "Zhongshan Mingyuan Kitchen Equipment", country: "China", website: "https://www.mingyuan.com", email: "export@mingyuan.com", city: "Zhongshan", categories: ["commercial-kitchens", "ose"], description: "Commercial kitchen and OS&E manufacturer. Hotel kitchen solutions for African hospitality market." },
]

const UAE: StrategicSupplier[] = [
  { companyName: "Al Ghurair Construction", country: "UAE", website: "https://www.alghurair.com", email: "construction@alghurair.com", city: "Dubai", categories: ["aluminium-systems", "glass-facades", "steel-structures"], description: "Major Dubai conglomerate. Aluminium systems, glass facades, and steel structures for hospitality and commercial projects across Africa." },
  { companyName: "Al Futtaim Group", country: "UAE", website: "https://www.alfuttaim.com", email: "info@alfuttaim.com", city: "Dubai", categories: ["hvac", "elevators", "building-materials"], description: "Leading UAE conglomerate. Represents global brands in HVAC, elevators, and building materials. Active in East Africa." },
  { companyName: "Emirates Steel Arkan", country: "UAE", website: "https://www.emiratessteel.com", email: "sales@emiratessteel.com", city: "Abu Dhabi", categories: ["steel-manufacturers", "rebar-manufacturers", "steel-structures"], description: "Largest steel manufacturer in UAE. Rebar, structural steel, and steel products. Exports to East African construction market." },
  { companyName: "Al Shirawi Enterprises", country: "UAE", website: "https://www.alshirawi.com", email: "info@alshirawi.com", city: "Dubai", categories: ["hvac", "steel-structures", "elevators"], description: "Diversified UAE group. HVAC, steel fabrication, elevators. Completed hospitality projects in Zanzibar and East Africa." },
  { companyName: "Summertown Modular", country: "UAE", website: "https://www.summertown.ae", email: "info@summertown.ae", city: "Dubai", categories: ["modular-buildings", "modular-hotels", "modular-villas", "prefab-houses"], description: "Dubai's leading modular construction company. Specializes in luxury modular hotels, villas, and resorts. Award-winning projects." },
  { companyName: "K4 Modular", country: "UAE", website: "https://www.k4modular.com", email: "info@k4modular.com", city: "Dubai", categories: ["modular-buildings", "modular-hotels", "container-homes"], description: "Innovative modular building solutions for hospitality. Container hotels and modular resorts for island and remote locations." },
  { companyName: "Depa Group", country: "UAE", website: "https://www.depa.com", email: "marketing@depa.com", city: "Dubai", categories: ["hotel-furniture", "ffe", "ose", "commercial-kitchens"], description: "Leading interior contracting and FF&E provider. Delivered 500+ hospitality projects worldwide including Africa. One-stop for hotel fit-out." },
  { companyName: "Al Taher Group", country: "UAE", website: "https://www.altahergroup.com", email: "info@altahergroup.com", city: "Sharjah", categories: ["hotel-furniture", "ffe", "ose"], description: "Premium hotel furniture and FF&E supplier. Serves 5-star hotels and resorts across Middle East and Africa." },
  { companyName: "Luxury Living Dubai", country: "UAE", website: "https://www.luxuryliving.ae", email: "info@luxuryliving.ae", city: "Dubai", categories: ["hotel-furniture", "ffe"], description: "High-end hotel FF&E supplier. Specializes in luxury resort furniture and villa interior solutions." },
  { companyName: "Schindler UAE", country: "UAE", website: "https://www.schindler.ae", email: "info.uae@schindler.com", city: "Dubai", categories: ["elevators"], description: "Schindler Middle East hub. Elevator and escalator solutions for hospitality and commercial projects in East Africa." },
  { companyName: "Johnson Controls Middle East", country: "UAE", website: "https://www.johnsoncontrols.com", email: "me.info@jci.com", city: "Dubai", categories: ["hvac"], description: "Global HVAC and building controls leader. Hotel HVAC solutions for African hospitality market." },
  { companyName: "Emirates Glass LLC", country: "UAE", website: "https://www.emiratesglass.com", email: "info@emiratesglass.com", city: "Dubai", categories: ["glass-facades", "aluminium-systems"], description: "Leading glass and aluminium facade manufacturer. Projects across Middle East and Africa. Hotel and commercial applications." },
  { companyName: "Dubai Cable Company (DUCT)", country: "UAE", website: "https://www.duct.ae", email: "info@duct.ae", city: "Dubai", categories: ["building-materials"], description: "Major cable and electrical products manufacturer. Serving hospitality and commercial projects across East Africa." },
  { companyName: "Al Sayegh Steel", country: "UAE", website: "https://www.alsayeghsteel.com", email: "info@alsayeghsteel.com", city: "Abu Dhabi", categories: ["steel-manufacturers", "steel-structures", "rebar-manufacturers"], description: "Major UAE steel manufacturer. Rebar, structural steel, and steel products for construction. Exports to Tanzania." },
  { companyName: "Emirates Cement Factory", country: "UAE", website: "https://www.emiratescement.com", email: "sales@emiratescement.com", city: "Abu Dhabi", categories: ["cement-manufacturers"], description: "Major UAE cement producer. Exports OPC and PPC cement to East African and Indian Ocean markets." },
  { companyName: "Interior FF&E Supply Dubai", country: "UAE", website: "https://www.interiorffe.com", email: "info@interiorffe.com", city: "Dubai", categories: ["ffe", "ose", "hotel-furniture"], description: "Dubai-based FF&E and OS&E procurement specialist. Serves hotel and resort projects throughout Africa." },
  { companyName: "Apex Modular Solutions", country: "UAE", website: "https://www.apexmodular.ae", email: "info@apexmodular.ae", city: "Dubai", categories: ["modular-buildings", "container-homes", "modular-hotels"], description: "Modular building solutions for remote and island locations. Experienced in East African hospitality market." },
]

const TURKEY: StrategicSupplier[] = [
  { companyName: "Tosyali Holding", country: "Turkey", website: "https://www.tosyali.com", email: "export@tosyali.com", city: "Istanbul", categories: ["steel-manufacturers", "rebar-manufacturers", "steel-structures"], description: "Turkey's largest steel producer. Rebar, wire rod, and structural steel. Major exporter to Africa with dedicated logistics." },
  { companyName: "Erdemir Group", country: "Turkey", website: "https://www.erdemir.com.tr", email: "export@erdemir.com.tr", city: "Eregli", categories: ["steel-manufacturers", "rebar-manufacturers"], description: "Leading Turkish steel manufacturer. Flat and long steel products. Strong export channel to East Africa." },
  { companyName: "Kardemir", country: "Turkey", website: "https://www.kardemir.com", email: "export@kardemir.com", city: "Karabuk", categories: ["steel-manufacturers", "rebar-manufacturers"], description: "Major Turkish integrated steel producer. Rebar, rail, and structural steel. Active in African construction market." },
  { companyName: "Sisecam Group", country: "Turkey", website: "https://www.sisecam.com", email: "export@sisecam.com", city: "Istanbul", categories: ["glass-facades", "aluminium-systems"], description: "World's 3rd largest glass manufacturer. Float glass, coated glass, and glass facade systems. Major African exporter." },
  { companyName: "Eczacibasi Building Products", country: "Turkey", website: "https://www.eczacibasi.com.tr", email: "export@eczacibasi.com.tr", city: "Istanbul", categories: ["building-materials", "aluminium-systems"], description: "Diversified building products group. Ceramics, sanitary ware, and building materials. Strong brand presence in East Africa." },
  { companyName: "Limak Cement Group", country: "Turkey", website: "https://www.limakcement.com", email: "export@limakcement.com", city: "Ankara", categories: ["cement-manufacturers"], description: "Major Turkish cement producer. Exports to 60+ countries including Tanzania and East Africa. OPC, PPC, and white cement." },
  { companyName: "Akcansa Cement", country: "Turkey", website: "https://www.akcansa.com.tr", email: "export@akcansa.com.tr", city: "Istanbul", categories: ["cement-manufacturers"], description: "Leading Turkish cement manufacturer. Sabancı Group joint venture. Exports comprehensive cement range to Africa." },
  { companyName: "Cimsa Cement", country: "Turkey", website: "https://www.cimsa.com.tr", email: "export@cimsa.com.tr", city: "Mersin", categories: ["cement-manufacturers"], description: "Specialized cement manufacturer. White cement, calcium aluminate cement. Serves African hospitality and construction sectors." },
  { companyName: "Kale Group", country: "Turkey", website: "https://www.kale.com.tr", email: "export@kale.com.tr", city: "Istanbul", categories: ["building-materials", "aluminium-systems"], description: "Leading Turkish building materials group. Aluminium systems, PVC, and building products. Strong African distribution network." },
  { companyName: "Istanbul Prefabrik", country: "Turkey", website: "https://www.istanbulprefabrik.com", email: "info@istanbulprefabrik.com", city: "Istanbul", categories: ["prefab-houses", "modular-buildings", "sandwich-panels"], description: "Leading Turkish prefab manufacturer. Export-ready prefab homes, modular buildings, and sandwich panels for African projects." },
  { companyName: "Modul Yapi", country: "Turkey", website: "https://www.mobilyapi.com", email: "export@mobilyapi.com", city: "Ankara", categories: ["modular-buildings", "modular-hotels", "prefab-houses"], description: "Modular construction specialist. Turnkey modular hotels and resorts for hospitality sector. Exports to 30+ countries." },
  { companyName: "Yildiz Hotel Furniture", country: "Turkey", website: "https://www.yildizhotelfurniture.com", email: "info@yildizhotelfurniture.com", city: "Istanbul", categories: ["hotel-furniture", "ffe", "ose"], description: "Top Turkish hotel furniture manufacturer. Full FF&E and OS&E for luxury hotels and resorts. Exports to Africa." },
  { companyName: "Ram Hotel Furniture", country: "Turkey", website: "https://www.rammobilya.com", email: "export@rammobilya.com", city: "Istanbul", categories: ["hotel-furniture", "ffe"], description: "Premium hotel furniture manufacturer. Contract furniture for international hotel chains. Active in Middle East and Africa." },
  { companyName: "Orta Hotel Textiles", country: "Turkey", website: "https://www.ortahoteltextile.com", email: "info@ortahoteltextile.com", city: "Denizli", categories: ["ffe", "ose"], description: "Leading hotel textile and linen manufacturer. Towels, bedding, curtains for hospitality. Exports to 80+ countries." },
  { companyName: "Arcelik Global", country: "Turkey", website: "https://www.arcelikglobal.com", email: "export@arcelik.com", city: "Istanbul", categories: ["hvac", "commercial-kitchens"], description: "Major Turkish appliance and HVAC manufacturer. Commercial cooling, kitchen equipment, and HVAC solutions for hospitality." },
  { companyName: "Vestel Commercial", country: "Turkey", website: "https://www.vestel.com.tr", email: "export@vestel.com.tr", city: "Manisa", categories: ["hvac", "commercial-kitchens"], description: "Major Turkish electronics and appliance manufacturer. HVAC systems and commercial kitchen equipment. Strong export network." },
  { companyName: "Feniş Aluminium", country: "Turkey", website: "https://www.fenis.com.tr", email: "export@fenis.com.tr", city: "Istanbul", categories: ["aluminium-systems", "glass-facades"], description: "Leading Turkish aluminium systems manufacturer. Curtain walls, window systems, and glass facades for commercial projects." },
  { companyName: "Panelsan Sandwich Panel", country: "Turkey", website: "https://www.panelsan.com", email: "export@panelsan.com", city: "Ankara", categories: ["sandwich-panels", "prefab-houses"], description: "Turkey's largest sandwich panel manufacturer. Insulated panels for cold storage, prefab buildings, and modular construction." },
  { companyName: "BMC Construction", country: "Turkey", website: "https://www.bmc.com.tr", email: "export@bmc.com.tr", city: "Izmir", categories: ["steel-structures", "modular-buildings"], description: "Steel structure and modular building manufacturer. Completed hospitality projects in Africa and Middle East." },
  { companyName: "Gülsan Group", country: "Turkey", website: "https://www.gulsan.com.tr", email: "export@gulsan.com.tr", city: "Gaziantep", categories: ["steel-manufacturers", "rebar-manufacturers"], description: "Major Turkish steel manufacturer. Rebar, wire rod, and profile steel. Exports to 70+ countries including East Africa." },
]

const INDIA: StrategicSupplier[] = [
  { companyName: "Tata Steel", country: "India", website: "https://www.tatasteel.com", email: "exports@tatasteel.com", city: "Mumbai", categories: ["steel-manufacturers", "rebar-manufacturers", "steel-structures"], description: "One of world's top steel companies. Comprehensive construction steel range. Strong presence in East Africa with offices in Tanzania." },
  { companyName: "JSW Steel", country: "India", website: "https://www.jswsteel.in", email: "exports@jsw.in", city: "Mumbai", categories: ["steel-manufacturers", "rebar-manufacturers"], description: "India's leading steel manufacturer. Rebar, structural steel, and coated products. Dedicated Africa export division." },
  { companyName: "SAIL", country: "India", website: "https://www.sail.co.in", email: "exports@sail.in", city: "New Delhi", categories: ["steel-manufacturers", "rebar-manufacturers"], description: "India's state-owned steel giant. Full range of construction steel. Exports to East Africa through established channels." },
  { companyName: "Jindal Steel & Power", country: "India", website: "https://www.jindalsteel.com", email: "exports@jindalsteel.com", city: "New Delhi", categories: ["steel-manufacturers", "rebar-manufacturers", "steel-structures"], description: "Major Indian steel and power company. Specialized in value-added steel products for construction. African export program." },
  { companyName: "UltraTech Cement", country: "India", website: "https://www.ultratechcement.com", email: "exports@ultratech.com", city: "Mumbai", categories: ["cement-manufacturers"], description: "India's largest cement manufacturer. Exports OPC, PPC, and specialized grades to Africa and Indian Ocean markets." },
  { companyName: "Ambuja Cements", country: "India", website: "https://www.ambujacement.com", email: "exports@ambuja.com", city: "Mumbai", categories: ["cement-manufacturers"], description: "Major Indian cement producer (Adani Group). Consistent exporter to Indian Ocean and East African markets." },
  { companyName: "Shree Cement", country: "India", website: "https://www.shreecement.in", email: "exports@shreecement.com", city: "Kolkata", categories: ["cement-manufacturers"], description: "Fastest growing Indian cement manufacturer. Export focus on East Africa and Indian Ocean islands." },
  { companyName: "Hindware Building Products", country: "India", website: "https://www.hindware.com", email: "exports@hindware.com", city: "New Delhi", categories: ["building-materials", "aluminium-systems"], description: "Leading Indian building products manufacturer. Sanitary ware, aluminium systems, and bathroom products. Strong in East Africa." },
  { companyName: "Jaquar & Company", country: "India", website: "https://www.jaquar.com", email: "exports@jaquar.com", city: "New Delhi", categories: ["building-materials", "hotel-furniture"], description: "Premium sanitary ware, lighting, and bathroom fittings. Preferred supplier for luxury hotels and resorts globally." },
  { companyName: "Kajaria Ceramics", country: "India", website: "https://www.kajariaceramics.com", email: "exports@kajaria.com", city: "New Delhi", categories: ["building-materials"], description: "India's largest tile manufacturer. Floor and wall tiles for hospitality and commercial projects. Active in East Africa." },
  { companyName: "Voltas (Tata Group)", country: "India", website: "https://www.voltas.com", email: "exports@voltas.com", city: "Mumbai", categories: ["hvac"], description: "Tata Group's HVAC arm. Commercial air conditioning for hotels and resorts. Established service network in East Africa." },
  { companyName: "Blue Star Limited", country: "India", website: "https://www.bluestarindia.com", email: "exports@bluestar.com", city: "Mumbai", categories: ["hvac"], description: "Leading Indian HVAC and commercial refrigeration company. Hotel HVAC solutions. Active in African hospitality market." },
  { companyName: "Tata Solar Power", country: "India", website: "https://www.tatapower.com", email: "solar.export@tatapower.com", city: "Mumbai", categories: ["solar-systems"], description: "Tata Group solar solutions. Complete solar PV systems for commercial and hospitality projects. Active in East Africa." },
  { companyName: "Vikram Solar", country: "India", website: "https://www.vikramsolar.com", email: "exports@vikramsolar.com", city: "Kolkata", categories: ["solar-systems"], description: "Top Indian solar module manufacturer. PV panels and systems for hospitality applications. Strong Africa pipeline." },
  { companyName: "Schindler India", country: "India", website: "https://www.schindlerindia.com", email: "info.india@schindler.com", city: "Mumbai", categories: ["elevators"], description: "Schindler India operations. Elevator and escalator solutions for hospitality and commercial buildings in East Africa." },
  { companyName: "Otis India", country: "India", website: "https://www.otis.com", email: "india.info@otis.com", city: "Mumbai", categories: ["elevators"], description: "Otis Elevator India hub. Serving African market with elevator and escalator solutions for hotels and commercial buildings." },
  { companyName: "Century Plyboards", country: "India", website: "https://www.centuryply.com", email: "exports@centuryply.com", city: "Kolkata", categories: ["ffe", "hotel-furniture"], description: "India's largest plywood and laminate manufacturer. Interior fit-out materials for hospitality projects. Active in East Africa." },
  { companyName: "Greenply Industries", country: "India", website: "https://www.greenply.com", email: "exports@greenply.com", city: "Kolkata", categories: ["ffe", "hotel-furniture"], description: "Major interior infrastructure company. Plywood, laminates, and interior products for hotel and commercial fit-outs." },
  { companyName: "Hettich India", country: "India", website: "https://www.hettich.com", email: "info.in@hettich.com", city: "Mumbai", categories: ["hotel-furniture", "ffe"], description: "German furniture fittings manufacturer in India. Kitchen and wardrobe fittings for hospitality furniture manufacturing." },
  { companyName: "Jindal Aluminium Limited", country: "India", website: "https://www.jindalaluminium.com", email: "exports@jindalaluminium.com", city: "Bangalore", categories: ["aluminium-systems"], description: "Leading Indian aluminium extrusion company. Architectural aluminium systems for facades, windows, and doors." },
  { companyName: "Motherson Sumi Systems", country: "India", website: "https://www.motherson.com", email: "info@motherson.com", city: "New Delhi", categories: ["building-materials"], description: "Global automotive and building components manufacturer. Electrical and lighting solutions for hospitality projects." },
  { companyName: "Bharat Heavy Electricals (BHEL)", country: "India", website: "https://www.bhel.com", email: "exports@bhel.com", city: "New Delhi", categories: ["solar-systems", "hvac"], description: "Indian state-owned engineering giant. Solar PV and HVAC systems for commercial and hospitality applications." },
  { companyName: "Godrej & Boyce (Facilities Management)", country: "India", website: "https://www.godrej.com", email: "exports@godrej.com", city: "Mumbai", categories: ["building-materials", "hvac"], description: "Diversified Indian conglomerate. Security solutions, HVAC, and building products for hospitality sector." },
  { companyName: "Asian Paints", country: "India", website: "https://www.asianpaints.com", email: "exports@asianpaints.com", city: "Mumbai", categories: ["building-materials"], description: "India's largest paint company. Complete paint and coating solutions for hospitality projects. Strong East African presence." },
]

const KENYA: StrategicSupplier[] = [
  { companyName: "Safal Group", country: "Kenya", website: "https://www.safalgroup.com", email: "info@safalgroup.com", city: "Nairobi", categories: ["steel-manufacturers", "rebar-manufacturers", "steel-structures"], description: "East Africa's largest steel producer. Rebar, steel sheets, and roofing products. Manufacturing in Kenya, Uganda, and Tanzania." },
  { companyName: "Devki Group", country: "Kenya", website: "https://www.devkisteel.com", email: "info@devkisteel.com", city: "Nairobi", categories: ["steel-manufacturers", "rebar-manufacturers", "cement-manufacturers"], description: "Kenya's largest steel and cement manufacturer. National Cement (Nyumba) and Devki Steel. Serving all East Africa." },
  { companyName: "Bamburi Cement (Lafarge)", country: "Kenya", website: "https://www.bamburi.com", email: "info@bamburi.com", city: "Mombasa", categories: ["cement-manufacturers"], description: "LafargeHolcim's Kenyan subsidiary. Leading cement producer for East Africa. Strong marine logistics to Zanzibar." },
  { companyName: "East African Portland Cement", country: "Kenya", website: "https://www.portlandcement.co.ke", email: "info@portlandcement.co.ke", city: "Nairobi", categories: ["cement-manufacturers"], description: "Kenyan cement manufacturer. Exports to Uganda, Tanzania, and Indian Ocean markets including Zanzibar." },
  { companyName: "Mabati Rolling Mills", country: "Kenya", website: "https://www.mabati.com", email: "info@mabati.com", city: "Mombasa", categories: ["steel-manufacturers", "building-materials"], description: "East Africa's premier roofing and steel sheet manufacturer. Major supplier to Zanzibar construction market." },
  { companyName: "Manji Building Materials", country: "Kenya", website: "https://www.manjigroup.com", email: "info@manjigroup.com", city: "Nairobi", categories: ["building-materials"], description: "Leading East African building materials distributor. Sanitary ware, tiles, fittings. Strong supply chain to Zanzibar." },
  { companyName: "Transafrica Building Supplies", country: "Kenya", website: "https://www.transafrica.co.ke", email: "info@transafrica.co.ke", city: "Nairobi", categories: ["building-materials", "aluminium-systems"], description: "Major building materials distributor in East Africa. Aluminium systems, glass, and construction materials." },
  { companyName: "Chandaria Industries", country: "Kenya", website: "https://www.chandaria.com", email: "info@chandaria.com", city: "Nairobi", categories: ["building-materials", "ffe"], description: "Diversified Kenyan manufacturer. Steel wool, aluminium products, and building materials. Serving East Africa for 50+ years." },
  { companyName: "Roca Sanitary Kenya", country: "Kenya", website: "https://www.roca.ke", email: "info@roca.ke", city: "Nairobi", categories: ["building-materials"], description: "Roca Group's Kenyan subsidiary. Premium sanitary ware, tiles, and bathroom solutions for hospitality projects." },
  { companyName: "Kenya Aluminium Works", country: "Kenya", website: "https://www.kaw.co.ke", email: "info@kaw.co.ke", city: "Nairobi", categories: ["aluminium-systems", "glass-facades"], description: "Leading aluminium and glass facade contractor in East Africa. Completed major hospitality projects in Zanzibar." },
  { companyName: "Davis & Shirtliff Group", country: "Kenya", website: "https://www.davisandshirtliff.com", email: "info@davisgroup.co.ke", city: "Nairobi", categories: ["solar-systems"], description: "East Africa's largest water and energy equipment supplier. Solar PV, water pumps, and HVAC for hospitality sector." },
  { companyName: "SolarKenya Limited", country: "Kenya", website: "https://www.solarkenya.com", email: "info@solarkenya.com", city: "Nairobi", categories: ["solar-systems"], description: "Leading Kenyan solar solutions provider. Commercial and hospitality solar installations. Active in Zanzibar market." },
  { companyName: "Prime Steel Kenya", country: "Kenya", website: "https://www.primesteel.co.ke", email: "info@primesteel.co.ke", city: "Nairobi", categories: ["steel-manufacturers", "rebar-manufacturers", "steel-structures"], description: "Major Kenyan steel manufacturer and fabricator. Structural steel, rebar, and steel products for construction." },
  { companyName: "Nationwide Electrical Industries", country: "Kenya", website: "https://www.nei.co.ke", email: "info@nei.co.ke", city: "Nairobi", categories: ["building-materials"], description: "Kenya's leading electrical and lighting manufacturer. Cables, lighting, and electrical products for hospitality projects." },
  { companyName: "Crown Paints Kenya", country: "Kenya", website: "https://www.crownpaints.co.ke", email: "info@crownpaints.co.ke", city: "Nairobi", categories: ["building-materials"], description: "Leading East African paint manufacturer. Complete coating solutions for hospitality and commercial projects in Zanzibar." },
  { companyName: "CFAO Kenya (Hotel Division)", country: "Kenya", website: "https://www.cfao.com", email: "info.kenya@cfao.com", city: "Nairobi", categories: ["hvac", "elevators", "commercial-kitchens"], description: "French multinational with strong East African presence. HVAC, elevators, and commercial kitchen solutions for hotels." },
  { companyName: "Bureau Veritas Kenya", country: "Kenya", website: "https://www.bureauveritas.co.ke", email: "info.kenya@bureauveritas.com", city: "Nairobi", categories: ["building-materials"], description: "Global testing and inspection provider. Construction quality assurance for hospitality projects in East Africa." },
  { companyName: "Twiga Hotel Supplies", country: "Kenya", website: "https://www.twiga.com", email: "info@twiga.com", city: "Nairobi", categories: ["hotel-furniture", "ffe", "ose", "commercial-kitchens"], description: "Kenya's largest hotel equipment and supplies distributor. Complete FF&E, OS&E, and commercial kitchen solutions for hospitality." },
  { companyName: "Al-Noor Furnishers", country: "Kenya", website: "https://www.alnoor.co.ke", email: "info@alnoor.co.ke", city: "Nairobi", categories: ["hotel-furniture", "ffe"], description: "Hotel and hospitality furniture specialist. Turnkey FF&E solutions for hotels and resorts across East Africa." },
]

const SOUTH_AFRICA: StrategicSupplier[] = [
  { companyName: "ArcelorMittal South Africa", country: "South Africa", website: "https://www.arcelormittalsa.com", email: "exports@arcelormittalsa.com", city: "Johannesburg", categories: ["steel-manufacturers", "rebar-manufacturers", "steel-structures"], description: "Part of world's largest steel group. Comprehensive steel products for construction. Exports throughout Africa." },
  { companyName: "AfriSam", country: "South Africa", website: "https://www.afrisam.com", email: "info@afrisam.com", city: "Johannesburg", categories: ["cement-manufacturers"], description: "Leading Southern African cement and construction materials company. Operations in Tanzania (AfriSam Tanzania). Ready-mix and aggregates." },
  { companyName: "PPC Cement", country: "South Africa", website: "https://www.ppcafrica.com", email: "exports@ppcafrica.com", city: "Johannesburg", categories: ["cement-manufacturers"], description: "Major African cement producer. Operations in South Africa, Botswana, Zimbabwe, Rwanda, and Ethiopia. Export capability to Zanzibar." },
  { companyName: "PG Group", country: "South Africa", website: "https://www.pggroup.co.za", email: "info@pggroup.co.za", city: "Johannesburg", categories: ["glass-facades", "aluminium-systems"], description: "Leading African glass and aluminium group. Glass facades, aluminium systems, and architectural glazing for hospitality projects." },
  { companyName: "Saint-Gobain South Africa", country: "South Africa", website: "https://www.saint-gobain.co.za", email: "info@saint-gobain.co.za", city: "Johannesburg", categories: ["glass-facades", "building-materials", "sandwich-panels"], description: "Global building materials leader. Gypsum, insulation, glass, and high-performance building solutions for hospitality." },
  { companyName: "Aluminium City", country: "South Africa", website: "https://www.aluminiumcity.co.za", email: "info@aluminiumcity.co.za", city: "Cape Town", categories: ["aluminium-systems", "glass-facades"], description: "Premium aluminium facade and window/door systems manufacturer. High-end solutions for hospitality architecture." },
  { companyName: "Sappi Limited", country: "South Africa", website: "https://www.sappi.com", email: "info@sappi.com", city: "Johannesburg", categories: ["building-materials"], description: "Global wood fibre and building materials company. Decorative laminates and interior building products for hotels." },
  { companyName: "Bell Equipment", country: "South Africa", website: "https://www.bellequipment.com", email: "info@bellequipment.com", city: "Richards Bay", categories: ["building-materials"], description: "Global heavy equipment manufacturer. ADTs, loaders, and articulated trucks for construction. Strong African distribution." },
  { companyName: "Murray & Roberts", country: "South Africa", website: "https://www.murrob.com", email: "info@murrob.com", city: "Johannesburg", categories: ["steel-structures", "building-materials"], description: "Major African engineering and construction group. Steel structures, mining, and building projects throughout Africa." },
  { companyName: "WBHO Construction", country: "South Africa", website: "https://www.wbho.co.za", email: "info@wbho.co.za", city: "Johannesburg", categories: ["steel-structures", "modular-buildings"], description: "One of Africa's largest construction companies. Hospitality and commercial building projects across the continent." },
  { companyName: "Johnson Controls South Africa", country: "South Africa", website: "https://www.johnsoncontrols.co.za", email: "info.sa@jci.com", city: "Johannesburg", categories: ["hvac"], description: "Global HVAC and building automation leader. Complete hotel HVAC solutions. Strong service network in Southern and East Africa." },
  { companyName: "Carrier South Africa", country: "South Africa", website: "https://www.carrier.co.za", email: "info.sa@carrier.com", city: "Johannesburg", categories: ["hvac"], description: "Global HVAC pioneer. Commercial air conditioning and refrigeration for hospitality projects throughout Africa." },
  { companyName: "Otis South Africa", country: "South Africa", website: "https://www.otis.com/za", email: "info.sa@otis.com", city: "Johannesburg", categories: ["elevators"], description: "Otis Elevator Southern Africa hub. Elevator and escalator service for hotels and commercial buildings in East Africa." },
  { companyName: "Schindler South Africa", country: "South Africa", website: "https://www.schindler.co.za", email: "info.sa@schindler.com", city: "Johannesburg", categories: ["elevators"], description: "Schindler Southern Africa. Elevator and escalator solutions for hospitality and commercial projects in Africa." },
  { companyName: "SolarWorld Africa", country: "South Africa", website: "https://www.solarworld.co.za", email: "info@solarworld.co.za", city: "Cape Town", categories: ["solar-systems"], description: "Leading solar solutions provider for African hospitality sector. PV, battery storage, and hybrid systems for remote resorts." },
  { companyName: "Alstone Ceilings", country: "South Africa", website: "https://www.alstone.co.za", email: "info@alstone.co.za", city: "Johannesburg", categories: ["building-materials"], description: "Leading African ceiling and partitioning manufacturer. Mineral fibre ceiling tiles, aluminium ceilings, and interior solutions." },
  { companyName: "Corobrik", country: "South Africa", website: "https://www.corobrik.co.za", email: "info@corobrik.co.za", city: "Durban", categories: ["building-materials"], description: "Leading South African brick and clay product manufacturer. Face bricks, pavers, and roof tiles. Premium hospitality finishes." },
  { companyName: "Hulett Aluminium (Tata Group)", country: "South Africa", website: "https://www.hulettaluminium.co.za", email: "info@hulettaluminium.co.za", city: "Pietermaritzburg", categories: ["aluminium-systems"], description: "Tata Group's African aluminium extrusion division. Architectural aluminium systems, profiles, and facade solutions." },
  { companyName: "Afriplex Hospitality Interiors", country: "South Africa", website: "https://www.afriplex.com", email: "info@afriplex.com", city: "Cape Town", categories: ["hotel-furniture", "ffe", "ose"], description: "Specialist hospitality interior supplier. FF&E, OS&E procurement and project management for African hotel and resort projects." },
  { companyName: "Marsden Hospitality", country: "South Africa", website: "https://www.marsdenhospitality.co.za", email: "info@marsdenhospitality.co.za", city: "Cape Town", categories: ["hotel-furniture", "ffe", "ose", "commercial-kitchens"], description: "Complete hospitality procurement specialist. FF&E, OS&E, and commercial kitchen solutions for luxury lodges and hotels in Africa." },
  { companyName: "Broll Hospitality", country: "South Africa", website: "https://www.broll.com", email: "hospitality@broll.com", city: "Johannesburg", categories: ["ffe", "ose", "hotel-furniture"], description: "Leading hospitality procurement and project management firm. FF&E, OS&E sourcing for African hotel developments." },
]

export const STRATEGIC_SUPPLIER_CATALOG: Record<string, StrategicSupplier[]> = {
  China: CHINA,
  UAE: UAE,
  Turkey: TURKEY,
  India: INDIA,
  Kenya: KENYA,
  "South Africa": SOUTH_AFRICA,
}

export function summarizeStrategic(): {
  total: number
  byCountry: Record<string, number>
  byCategory: Record<string, number>
} {
  const byCountry: Record<string, number> = {}
  const byCategory: Record<string, number> = {}
  let total = 0

  for (const [country, suppliers] of Object.entries(STRATEGIC_SUPPLIER_CATALOG)) {
    byCountry[country] = suppliers.length
    total += suppliers.length
    for (const s of suppliers) {
      for (const c of s.categories) {
        byCategory[c] = (byCategory[c] || 0) + 1
      }
    }
  }
  return { total, byCountry, byCategory }
}
